# Generated by Django 6.0.1 on 2026-01-29 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_alter_item_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.list')),
            ],
        ),
    ]
