# Generated by Django 6.0.1 on 2026-02-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
