# Generated by Django 6.0.2 on 2026-02-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_item_priority_delete_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
